### ISSUE TITLE
What is the current state of this?

### ISSUE THREAD

**Issue by Hisairnessag3** [bradleyhurley/PyBall#37]
This looks to be the only promising mlbstats api python implementation, however it seems there is a lot to be done to get even basic stats. Are currently implemented? Like hits,ERA, avg on a team or player granularity? Perhaps I am just being a bit dense.

**Comment by bradleyhurley** [comment]
Thanks for your interest in the library, but the things you described are the functionality you could implement with this API wrapper. 

I have a pull request open to add more functionality, and plan to make working with players easier, but don't plan on exposing stats that can be calculated based on data returned by MLB.
